In [1]:
import nltk

import numpy as np

import numpy as np
import matplotlib
matplotlib.use('agg')
import matplotlib.pyplot as plt
plt.rcParams['figure.figsize'] = [10, 5]


In [2]:
# nltk.download('wordnet')

In [6]:
# e.g. synonym sets containing “good”:
poses = { 'n':'noun', 'v':'verb', 's':'adj (s)', 'a':'adj', 'r':'adv'}
for synset in wn.synsets("good"):
    print("{}: {}".format(poses[synset.pos()],
    ", ".join([l.name() for l in synset.lemmas()])))

noun: good
noun: good, goodness
noun: good, goodness
noun: commodity, trade_good, good
adj: good
adj (s): full, good
adj: good
adj (s): estimable, good, honorable, respectable
adj (s): beneficial, good
adj (s): good
adj (s): good, just, upright
adj (s): adept, expert, good, practiced, proficient, skillful, skilful
adj (s): good
adj (s): dear, good, near
adj (s): dependable, good, safe, secure
adj (s): good, right, ripe
adj (s): good, well
adj (s): effective, good, in_effect, in_force
adj (s): good
adj (s): good, serious
adj (s): good, sound
adj (s): good, salutary
adj (s): good, honest
adj (s): good, undecomposed, unspoiled, unspoilt
adj (s): good
adv: well, good
adv: thoroughly, soundly, good


In [8]:
# e.g. hypernyms of “panda”:
panda = wn.synset("panda.n.01")
hyper = lambda s: s.hypernyms()
list(panda.closure(hyper))

[Synset('procyonid.n.01'),
 Synset('carnivore.n.01'),
 Synset('placental.n.01'),
 Synset('mammal.n.01'),
 Synset('vertebrate.n.01'),
 Synset('chordate.n.01'),
 Synset('animal.n.01'),
 Synset('organism.n.01'),
 Synset('living_thing.n.01'),
 Synset('whole.n.02'),
 Synset('object.n.01'),
 Synset('physical_entity.n.01'),
 Synset('entity.n.01')]

In [63]:
corpus = ["START All that glitters isn't gold END".split(" "), 
          "START All's well that ends well END".split(" "),
         "START All that that isn't glitters END".split(" "),]
corpus

[['START', 'All', 'that', 'glitters', "isn't", 'gold', 'END'],
 ['START', "All's", 'well', 'that', 'ends', 'well', 'END'],
 ['START', 'All', 'that', 'that', "isn't", 'glitters', 'END']]

In [172]:
def distinct_words(corpus):
    """ Determine a list of distinct words for the corpus.
        Params:
            corpus (list of list of strings): corpus of documents
        Return:
            corpus_words (list of strings): list of distinct words across the corpus, sorted (using python 'sorted' function)
            num_corpus_words (integer): number of distinct words across the corpus
    """
    corpus_words = []
    num_corpus_words = -1
    
### SOLUTION BEGIN
    words = set()
    for doc in corpus:
        words.update([word for word in doc])
    corpus_words = sorted(words)
    num_corpus_words = len(words)
### SOLUTION END

    return corpus_words, num_corpus_words

words, num_words = distinct_words(corpus)
word2Ind = {}
for i, word in enumerate(words):
    word2Ind[word] = i
print(word2Ind)

NameError: name 'corpus' is not defined

In [65]:
corpus_index = np.array([[word2Ind[word] for word in doc] for doc in corpus])
corpus_index

array([[3, 0, 8, 5, 7, 6, 2],
       [3, 1, 9, 8, 4, 9, 2],
       [3, 0, 8, 8, 7, 5, 2]])

In [79]:
found_word_positions = np.where(corpus_index == 8)
print(found_word_positions)
print(type(found_word_positions))
for t in np.array(found_word_positions).T:
    doc_index = t[0]
    wi = t[1]
    print(f"doc_index: {doc_index} wi: {wi}")

(array([0, 1, 2, 2]), array([2, 3, 2, 3]))
<class 'tuple'>
doc_index: 0 wi: 2
doc_index: 1 wi: 3
doc_index: 2 wi: 2
doc_index: 2 wi: 3


In [60]:
a = 'START'
for doc in corpus:
    for wi, ww in enumerate(doc):
        if ww == a:
            print(f"wi: {wi}")



wi: 0
wi: 0
wi: 0


In [15]:
a = np.array([1, 2, 3])   # Create a rank 1 array
print(type(a))            # Prints "<class 'numpy.ndarray'>"
print(a.shape)            # Prints "(3,)"
print(a[0], a[1], a[2])   # Prints "1 2 3"
a[0] = 5                  # Change an element of the array
print(a)                  # Prints "[5, 2, 3]"

b = np.array([[1,2,3],[4,5,6]])    # Create a rank 2 array
print(b.shape)                     # Prints "(2, 3)"
print(b[0, 0], b[0, 1], b[1, 0])   # Prints "1 2 4"

<class 'numpy.ndarray'>
(3,)
1 2 3
[5 2 3]
(2, 3)
1 2 4


In [24]:
import numpy as np

a = np.array([[1,2], [3, 4], [5, 6]])
print(f"a.shape {a.shape}")
print(a)
print("")

bool_idx = (a > 2)   # Find the elements of a that are bigger than 2;
                     # this returns a numpy array of Booleans of the same
                     # shape as a, where each slot of bool_idx tells
                     # whether that element of a is > 2.

print(bool_idx)      # Prints "[[False False]
                     #          [ True  True]
                     #          [ True  True]]"

# We use boolean array indexing to construct a rank 1 array
# consisting of the elements of a corresponding to the True values
# of bool_idx
print(a[bool_idx])  # Prints "[3 4 5 6]"

# We can do all of the above in a single concise statement:
print(a[a > 2])     # Prints "[3 4 5 6]"


a.shape (3, 2)
[[1 2]
 [3 4]
 [5 6]]

[[False False]
 [ True  True]
 [ True  True]]
[3 4 5 6]
[3 4 5 6]


In [36]:
arr = np.array([11, 12, 13, 14, 15, 16, 17, 15, 11, 12, 14, 15, 16, 17])
# Get the index of elements with value 15
result = np.where(arr == 15)
print('Tuple of arrays returned : ', result)
print("Elements with value 15 exists at following indices", result[0], sep='\n')

Tuple of arrays returned :  (array([ 4,  7, 11]),)
Elements with value 15 exists at following indices
[ 4  7 11]


In [80]:
    # "START All that glitters isn't gold END"
    # "START All's well that ends well END"
    # print(word_context(corpus[0], 0, 4))

    # str = "START All that glitters isn't gold END".split(" ")
    # print(f"f0: {word_context(str, 0, 2)}")
    # print(f"f1: {word_context(str, 1, 2)}")
    # print(f"f2: {word_context(str, 2, 2)}")
    # print(f"f3: {word_context(str, 3, 2)}")
    # print(f"f4: {word_context(str, 4, 2)}")
    # print(f"f5: {word_context(str, 5, 2)}")
    # print(f"f6: {word_context(str, 6, 2)}")
    # return


### SVD

https://davetang.org/file/Singular_Value_Decomposition_Tutorial.pdf

## Assigment 1

In [5]:
import nltk
nltk.download('reuters')
from nltk.corpus import reuters

START_TOKEN = '<START>'
END_TOKEN = '<END>'

def read_corpus(category="crude"):
    """ Read files from the specified Reuter's category.
        Params:
            category (string): category name
        Return:
            list of lists, with words from each of the processed files
    """
    files = reuters.fileids(category)
    return [[START_TOKEN] + [w.lower() for w in list(reuters.words(f))] + [END_TOKEN] for f in files]


[nltk_data] Downloading package reuters to
[nltk_data]     /Users/yrybitskyi/nltk_data...
[nltk_data]   Package reuters is already up-to-date!


In [6]:
reuters_corpus = read_corpus()

In [307]:
import sys
import os
import numpy as np
import scipy as sp
from sklearn.decomposition import TruncatedSVD
from sklearn.decomposition import PCA


In [315]:
def distinct_words(corpus):
    """ Determine a list of distinct words for the corpus.
        Params:
            corpus (list of list of strings): corpus of documents
        Return:
            corpus_words (list of strings): list of distinct words across the corpus, sorted (using python 'sorted' function)
            num_corpus_words (integer): number of distinct words across the corpus
    """
    corpus_words = []
    num_corpus_words = -1
    
### SOLUTION BEGIN
    words = set()
    def is_word(s):
        s = s.replace("'", "")
        if len(s) == 0:
            return False
        if s.isdigit():
            return False
        return s.isalnum()

    for doc in corpus:
        words.update([word for word in doc if is_word(word)])

    corpus_words = sorted(words)
    num_corpus_words = len(words)
### SOLUTION END

    return corpus_words, num_corpus_words

In [316]:
def compute_co_occurrence_matrix(corpus, window_size=4):
    """ Compute co-occurrence matrix for the given corpus and window_size (default of 4).
    
        Note: Each word in a document should be at the center of a window. Words near edges will have a smaller
              number of co-occurring words.
              
              For example, if we take the document "START All that glitters is not gold END" with window size of 4,
              "All" will co-occur with "START", "that", "glitters", "is", and "not".
    
        Params:
            corpus (list of list of strings): corpus of documents
            window_size (int): size of context window
        Return:
            M (numpy matrix of shape (number of unique words in the corpus , number of unique words in the corpus)):
                Co-occurrence matrix of word counts. 
                The ordering of the words in the rows/columns should be the same as the ordering of the words given by the distinct_words function.
            word2Ind (dict): dictionary that maps word to index (i.e. row/column number) for matrix M.
    """
    words, num_words = distinct_words(corpus)
    M = None
    word2Ind = {}

    ### SOLUTION BEGIN

    for i, word in enumerate(words):
        word2Ind[word] = i

    def relu(x):
        if x > 0:
            return x
        else:
            return 0

    # + 1. remove second is_word function
    # 2. cache word existing
    # 3. skip j rows that are not used in j rows
    # + 4. fix 2pac


    # def is_word(s):
    #     s = s.replace("'", "")
    #     return len(s) > 1 and s[0].isalpha() and s.isalnum()

    max_doc_length = 0
    for doc in corpus:
        doc_length = len(doc)
        if doc_length > max_doc_length:
            max_doc_length = doc_length


    corpus_index = np.zeros((len(corpus), max_doc_length))
    skipped_words = set()
    for i, doc in enumerate(corpus):
        for j, word in enumerate(doc):
            w_idx = word2Ind.get(word)
            if w_idx is not None:
                corpus_index[i, j] = w_idx
            else:
                skipped_words.add(word)

    print(f"skipped_words : {sorted(skipped_words)}")

    print(f"corpus_index.shape: {corpus_index.shape}")
    def word_context(doc_index, word_index, wd_size):
        word_context_map = {}

        doc = corpus_index[doc_index]
        left_context = doc[relu(word_index - wd_size) : word_index]
        right_context = doc[word_index + 1 : word_index + wd_size + 1]

        for w in left_context:
            cnt = word_context_map.get(w, 0)
            word_context_map[w] = cnt + 1
        for w in right_context:
            cnt = word_context_map.get(w, 0)
            word_context_map[w] = cnt + 1

        return word_context_map

    # M = np.zeros((num_words, num_words))
    M = np.empty((num_words, num_words))
    M[:] = np.nan

    # Cache all words in corpus
    # word_presence = np.empty(num_words)
    word_presence = [None] * num_words
    for i in range(num_words):
        word_presence[i] = np.array(np.where(corpus_index == i)).T


    #
    for i in range(num_words):
        # a = words[i]
        # print(f"{i} '{a}' from {num_words}")
        print(f"{i} from {num_words}")
        i_word_presence = word_presence[i]
        for j in range(num_words):
            if i == j:
                M[i, j] = 0
                continue
            if np.isnan(M[j, i]):
                cnt = 0
                # a_idx = word2Ind[a]
                # found_word_positions = np.where(corpus_index == a_idx)
                # for t in np.array(found_word_positions).T:
                for t in i_word_presence:
                    doc_index = t[0]
                    wi = t[1]
                    word_context_map = word_context(doc_index, wi, window_size)
                    cnt = cnt + word_context_map.get(j, 0)

                M[i, j] = cnt
            else:
                M[i, j] = M[j, i]

### SOLUTION END

    return M, word2Ind

In [317]:
def reduce_to_k_dim(M, k=2):
    """ Reduce a co-occurrence count matrix of dimensionality (num_corpus_words, num_corpus_words)
        to a matrix of dimensionality (num_corpus_words, k) using the following SVD function from Scikit-Learn:
            - http://scikit-learn.org/stable/modules/generated/sklearn.decomposition.TruncatedSVD.html
    
        Params:
            M (numpy matrix of shape (number of unique words in the corpus , number of number of corpus words)): co-occurrence matrix of word counts
            k (int): embedding size of each word after dimension reduction
        Return:
            M_reduced (numpy matrix of shape (number of corpus words, k)): matrix of k-dimensioal word embeddings.
                    In terms of the SVD from math class, this actually returns U * S
    """    
    np.random.seed(4355)
    n_iters = 10     # Use this parameter in your call to `TruncatedSVD`
    M_reduced = None
    print("Running Truncated SVD over %i words..." % (M.shape[0]))
    
    ### SOLUTION BEGIN
    svd = TruncatedSVD(n_components=k, n_iter=n_iters)
    M_reduced = svd.fit_transform(M)
    ### SOLUTION END

    print("Done.")
    return M_reduced

In [319]:
M_co_occurrence, word2Ind_co_occurrence = compute_co_occurrence_matrix(reuters_corpus[:10])
cnt = np.count_nonzero(M_co_occurrence > 0)
if np.count_nonzero(M_co_occurrence > 0) == 0:
    raise Exception("Matrix's empty")
print(f"Result Matrix Count: {cnt}")

skipped_words : ['"', '&', "'", '(', ')', '),', ',', ',"', '-', '.', '."', '.)', '/', '0', '000', '04', '08', '09', '1', '10', '100', '106', '13', '15', '16', '165', '178', '1978', '1985', '1986', '1987', '199', '1990', '2', '20', '200', '2000', '21', '23', '248', '25', '26', '27', '28', '3', '30', '300', '31', '335', '35', '371', '38', '39', '4', '40', '42', '5', '511', '520', '54', '550', '555', '56', '561', '57', '58', '6', '600', '63', '65', '7', '700', '71', '73', '741', '76', '8', '9', '90', '92', '98', '99', ';', '<END>', '<START>', '>', '>,', '>.']
corpus_index.shape: (10, 1001)
0 from 800
1 from 800
2 from 800
3 from 800
4 from 800
5 from 800
6 from 800
7 from 800
8 from 800
9 from 800
10 from 800
11 from 800
12 from 800
13 from 800
14 from 800
15 from 800
16 from 800
17 from 800
18 from 800
19 from 800
20 from 800
21 from 800
22 from 800
23 from 800
24 from 800
25 from 800
26 from 800
27 from 800
28 from 800
29 from 800
30 from 800
31 from 800
32 from 800
33 from 800
34 from 

630 from 800
631 from 800
632 from 800
633 from 800
634 from 800
635 from 800
636 from 800
637 from 800
638 from 800
639 from 800
640 from 800
641 from 800
642 from 800
643 from 800
644 from 800
645 from 800
646 from 800
647 from 800
648 from 800
649 from 800
650 from 800
651 from 800
652 from 800
653 from 800
654 from 800
655 from 800
656 from 800
657 from 800
658 from 800
659 from 800
660 from 800
661 from 800
662 from 800
663 from 800
664 from 800
665 from 800
666 from 800
667 from 800
668 from 800
669 from 800
670 from 800
671 from 800
672 from 800
673 from 800
674 from 800
675 from 800
676 from 800
677 from 800
678 from 800
679 from 800
680 from 800
681 from 800
682 from 800
683 from 800
684 from 800
685 from 800
686 from 800
687 from 800
688 from 800
689 from 800
690 from 800
691 from 800
692 from 800
693 from 800
694 from 800
695 from 800
696 from 800
697 from 800
698 from 800
699 from 800
700 from 800
701 from 800
702 from 800
703 from 800
704 from 800
705 from 800
706 from 800

In [320]:
M_co_occurrence

array([[ 0., 39.,  5., ...,  1.,  0.,  1.],
       [39.,  0.,  1., ...,  0.,  1.,  1.],
       [ 5.,  1.,  0., ...,  0.,  0.,  0.],
       ...,
       [ 1.,  0.,  0., ...,  0.,  0.,  0.],
       [ 0.,  1.,  0., ...,  0.,  0.,  0.],
       [ 1.,  1.,  0., ...,  0.,  0.,  0.]])

In [321]:
M_reduced_co_occurrence = reduce_to_k_dim(M_co_occurrence, k=2)
print(M_reduced_co_occurrence.size)

Running Truncated SVD over 800 words...
Done.
1600


In [322]:
M_lengths = np.linalg.norm(M_reduced_co_occurrence, axis=1)
M_normalized = M_reduced_co_occurrence / M_lengths[:, np.newaxis] # broadcasting

In [323]:
def plot_embeddings(M_reduced, word2Ind, words, title):
    plt.clf()
    for word in words:
        idx = word2Ind[word]
        x = M_reduced[idx, 0]
        y = M_reduced[idx, 1]
        plt.scatter(x, y, marker='x', color='red')
        plt.text(x, y, word, fontsize=9)
    plt.savefig(title)


In [324]:
M_normalized.size

1600

In [325]:
M_reduced_co_occurrence.size

1600

In [327]:
# words_list = ['barrels', 'bpd', 'ecuador', 'energy', 'industry', 'kuwait', 'oil', 'output', 'petroleum', 'venezuela']
words_list = ['barrels', 'energy', 'industry', 'oil', 'petroleum']
# words_list = ['an', 'year']
# words_list = ['barrels', 'bpd']

plot_embeddings(M_normalized, word2Ind_co_occurrence, words_list, 'co_occurrence_embeddings5.png')


KeyError: 'ecuador'

In [270]:
# Calc only diagonal

In [271]:
# store doc_index as max words only

In [304]:
# 2pac bug
# do not filter out tokens that starts from number