In [9]:
import torch
import torch.nn as nn
import torch.nn.functional as F
import torch.nn.utils

In [14]:
embedding = nn.Embedding(10, 3)
# a batch of 2 samples of 4 indices each
input = torch.LongTensor([
    [1,2,4,5],
    [4,3,2,9]])
embedding(input)

tensor([[[-1.8945, -0.4905,  1.8008],
         [ 1.2285, -0.5103,  0.0439],
         [ 0.3994,  1.6089,  2.2341],
         [-1.2144,  0.5555,  0.1739]],

        [[ 0.3994,  1.6089,  2.2341],
         [-1.5616, -0.5086,  0.6571],
         [ 1.2285, -0.5103,  0.0439],
         [ 0.4517,  0.5417,  1.4124]]], grad_fn=<EmbeddingBackward>)

In [17]:
rnn = nn.LSTM(10, 20, 2)
input = torch.randn(5, 3, 10)
h0 = torch.randn(2, 3, 20)
c0 = torch.randn(2, 3, 20)
output, (hn, cn) = rnn(input, (h0, c0))
print(output)

tensor([[[-2.3981e-01,  4.1244e-01,  9.3115e-02, -4.3005e-02,  3.3042e-01,
           4.9218e-01,  3.7417e-01, -2.0643e-01, -3.7912e-01, -3.0800e-01,
          -4.0150e-01,  1.1727e-01, -1.5637e-01,  2.9471e-01,  4.0225e-01,
          -5.9101e-03, -3.6909e-01, -1.5997e-01,  2.0782e-01, -7.4707e-02],
         [-2.5770e-01, -3.5434e-01, -8.2726e-02, -5.3464e-02, -1.2011e-01,
          -2.3071e-01, -2.2129e-01,  1.7346e-01,  4.4689e-01,  4.0703e-01,
          -8.5959e-02, -3.3974e-01, -9.0958e-02,  4.3275e-02,  1.8130e-01,
           1.0109e-01, -8.7431e-02, -3.2915e-01,  5.8454e-03,  5.3383e-02],
         [ 2.1184e-02,  9.4610e-02,  2.2474e-01,  7.8041e-02, -4.7218e-01,
           7.6736e-03,  1.4212e-01,  9.8716e-02, -4.1600e-01,  2.3166e-02,
          -1.2764e-01, -1.7493e-01,  1.0264e-01,  9.0554e-02,  2.2718e-01,
           3.0260e-01,  1.7041e-01,  1.9831e-01,  4.7464e-02, -6.2420e-02]],

        [[-1.3027e-01,  2.6094e-01, -6.1043e-02,  7.4563e-02,  1.9213e-01,
           1.7708e-0

In [18]:
print(hn)

tensor([[[ 0.0011, -0.1135,  0.0872,  0.0540,  0.1491,  0.0086,  0.0887,
           0.1340, -0.1681, -0.0911, -0.0419,  0.0260, -0.1590, -0.1021,
          -0.1187, -0.0293, -0.0313, -0.0276,  0.1172, -0.0287],
         [ 0.1614, -0.0906, -0.0811,  0.2315,  0.0791, -0.0470,  0.1031,
           0.1969, -0.0621,  0.0675, -0.1078,  0.1111, -0.0810, -0.1112,
          -0.2056, -0.0300,  0.3398,  0.0385, -0.1096,  0.1899],
         [-0.0211, -0.2226,  0.1302,  0.0879,  0.1321,  0.0803,  0.0397,
           0.0993,  0.1699,  0.0254, -0.1395, -0.0564, -0.0825, -0.0120,
          -0.1214, -0.0250,  0.1474, -0.0902, -0.2316,  0.0129]],

        [[-0.0862,  0.0513, -0.1816,  0.1661,  0.1373,  0.0474,  0.1791,
          -0.1373, -0.0188, -0.0464, -0.1087,  0.1115, -0.0583,  0.0540,
          -0.0218,  0.0907,  0.0767, -0.1367, -0.0438,  0.1173],
         [-0.0439, -0.0231, -0.1766,  0.1221,  0.1215,  0.0185,  0.1100,
          -0.0992,  0.0469,  0.0031, -0.1167,  0.0702, -0.0272, -0.0180,
        

In [19]:
print(cn)

tensor([[[ 0.0031, -0.2045,  0.1520,  0.1789,  0.2619,  0.0266,  0.1676,
           0.2362, -0.2677, -0.3277, -0.0755,  0.0961, -0.2326, -0.3098,
          -0.2753, -0.0529, -0.0734, -0.0715,  0.2048, -0.0665],
         [ 0.2492, -0.1699, -0.4277,  0.3743,  0.1811, -0.0814,  0.2711,
           0.3729, -0.1715,  0.1167, -0.1954,  0.1640, -0.2957, -0.2118,
          -0.3565, -0.0746,  0.7637,  0.0523, -0.1743,  0.4650],
         [-0.0532, -0.3761,  0.2668,  0.1595,  0.2704,  0.1657,  0.0887,
           0.2057,  0.2735,  0.0660, -0.2263, -0.0924, -0.1847, -0.0421,
          -0.2036, -0.0421,  0.2677, -0.1778, -0.4042,  0.0306]],

        [[-0.1810,  0.0985, -0.4140,  0.3191,  0.3127,  0.0959,  0.3246,
          -0.2509, -0.0379, -0.0957, -0.2389,  0.2007, -0.1323,  0.0995,
          -0.0433,  0.1880,  0.1647, -0.2824, -0.0907,  0.2521],
         [-0.0878, -0.0406, -0.4056,  0.2319,  0.2666,  0.0367,  0.1917,
          -0.1629,  0.0962,  0.0064, -0.2402,  0.1326, -0.0595, -0.0311,
        

In [22]:
x = torch.randn(2, 3, 5)
print(x.size())

print(x.permute(2, 0, 1).size())

torch.Size([2, 3, 5])
torch.Size([5, 2, 3])


In [23]:
x

tensor([[[ 1.1236, -0.8771,  1.6650, -0.7788, -0.5144],
         [ 0.1326, -0.3312, -0.2867, -2.4830,  0.1034],
         [ 0.7673,  0.3375,  2.1390,  0.8000,  0.2405]],

        [[-0.0153, -0.7367, -0.6222,  0.7282,  1.3127],
         [ 0.1567,  0.9879,  0.0679,  0.2071,  1.2133],
         [ 0.0398, -1.4301,  0.1342,  1.5115, -0.7954]]])

In [ ]:
#`last_hidden` is a tensor shape (2, b, h). 
# The first dimension corresponds to forwards and backwards.
# Concatenate the forwards and backwards tensors to obtain a tensor shape (b, 2*h)
t = torch.Long

In [25]:
x = torch.randn(2, 3)
x

tensor([[ 0.7709,  0.4804, -0.7546],
        [-1.0612, -0.9621,  0.6827]])

In [27]:
torch.cat((x, x, x), 0)

tensor([[ 1.5419,  0.9608, -1.5092],
        [-2.1223, -1.9242,  1.3655],
        [ 0.7709,  0.4804, -0.7546],
        [-1.0612, -0.9621,  0.6827],
        [ 0.7709,  0.4804, -0.7546],
        [-1.0612, -0.9621,  0.6827]])

In [24]:
print(x.permute(2, 0, 1))

tensor([[[ 1.1236,  0.1326,  0.7673],
         [-0.0153,  0.1567,  0.0398]],

        [[-0.8771, -0.3312,  0.3375],
         [-0.7367,  0.9879, -1.4301]],

        [[ 1.6650, -0.2867,  2.1390],
         [-0.6222,  0.0679,  0.1342]],

        [[-0.7788, -2.4830,  0.8000],
         [ 0.7282,  0.2071,  1.5115]],

        [[-0.5144,  0.1034,  0.2405],
         [ 1.3127,  1.2133, -0.7954]]])


In [67]:
# (2, b, h)
# b = 3, h = 4
# => (b, 2 * h) = (3, 8)
t = torch.randn(2, 3, 4)
t

tensor([[[ 2.1341, -0.8052, -0.2350, -1.4083],
         [ 0.3253, -0.1871, -1.6087, -0.5147],
         [-1.4240,  0.1252,  1.2401, -0.5109]],

        [[ 0.5926,  0.5028,  0.8743, -0.4543],
         [-0.7226, -2.3409, -0.3698,  1.2367],
         [-0.4589,  0.8747,  1.5771,  0.2315]]])

In [63]:
t.permute(1, 0, 2)

tensor([[[-1.9475, -0.5888,  0.2962,  0.0940],
         [-1.5057, -0.1350, -0.0663,  0.8253]],

        [[ 0.6143, -1.3169,  0.0201,  0.5985],
         [-1.2832, -1.6516, -0.5532,  0.0996]],

        [[-0.6298,  2.2231,  0.0355, -1.8010],
         [-0.8459, -0.1034, -0.0581,  0.4544]]])

In [69]:
torch.cat((t[0], t[1]), 1).size()

torch.Size([3, 8])

In [49]:
x = torch.randn(2, 3)
x

tensor([[ 0.0605, -1.2572, -1.2634],
        [ 0.1701,  1.7426,  0.3927]])

In [52]:
y = torch.randn(2, 3)
y

tensor([[ 0.2881,  0.0913, -0.0089],
        [-1.1232,  0.7478,  1.2241]])

In [54]:
torch.cat((x, y), 1)

tensor([[ 0.0605, -1.2572, -1.2634,  0.2881,  0.0913, -0.0089],
        [ 0.1701,  1.7426,  0.3927, -1.1232,  0.7478,  1.2241]])

In [70]:
from torch.nn.utils.rnn import pack_padded_sequence, pad_packed_sequence

seq = torch.tensor([[1,2,0], [3,0,0], [4,5,6]])
lens = [2, 1, 3]
packed = pack_padded_sequence(seq, lens, batch_first=True, enforce_sorted=False)
packed

PackedSequence(data=tensor([4, 1, 3, 5, 2, 6]), batch_sizes=tensor([3, 2, 1]), sorted_indices=tensor([2, 0, 1]), unsorted_indices=tensor([1, 2, 0]))

In [72]:
seq_unpacked, lens_unpacked = pad_packed_sequence(packed, batch_first=True)
seq_unpacked

tensor([[1, 2, 0],
        [3, 0, 0],
        [4, 5, 6]])

In [73]:
lens_unpacked

tensor([2, 1, 3])

In [78]:
Y = torch.arange(4*5*3).reshape(4,5,3)
Y

tensor([[[ 0,  1,  2],
         [ 3,  4,  5],
         [ 6,  7,  8],
         [ 9, 10, 11],
         [12, 13, 14]],

        [[15, 16, 17],
         [18, 19, 20],
         [21, 22, 23],
         [24, 25, 26],
         [27, 28, 29]],

        [[30, 31, 32],
         [33, 34, 35],
         [36, 37, 38],
         [39, 40, 41],
         [42, 43, 44]],

        [[45, 46, 47],
         [48, 49, 50],
         [51, 52, 53],
         [54, 55, 56],
         [57, 58, 59]]])

In [85]:
for Y_t in torch.split(Y, 1):
    print(f"Y_t.size: {Y_t.size()}")
    Y_t = torch.squeeze(Y_t)
    print(f"Y_t.size after squeeze: {Y_t.size()}")
    break

Y_t.size: torch.Size([1, 5, 3])
Y_t.size after squeeze: torch.Size([5, 3])


In [89]:
input = torch.randn(2, 3)
input

tensor([[ 1.2485, -0.8024,  2.0375],
        [-0.0478,  2.2435, -0.6559]])

In [100]:
m = nn.Softmax(dim=0)

In [101]:
output = m(input)
output

tensor([[0.7852, 0.0454, 0.9366],
        [0.2148, 0.9546, 0.0634]])

In [105]:
dec_hidden = torch.randn(5, 3)
enc_hiddens_proj = torch.randn(5, 20, 3)
print(f"dec_hidden.size: {dec_hidden.size()} enc_hiddens_proj.size: {enc_hiddens_proj.size()}")

dec_hidden.size: torch.Size([5, 3]) enc_hiddens_proj.size: torch.Size([5, 20, 3])


In [111]:
dec_hidden.unsqueeze(2).size()

torch.Size([5, 3, 1])

In [112]:
enc_hiddens_proj.bmm(dec_hidden.unsqueeze(2)).size()

torch.Size([5, 20, 1])

In [113]:
enc_hiddens_proj.bmm(dec_hidden.unsqueeze(2)).squeeze(2).size()

torch.Size([5, 20])

In [114]:
enc_hiddens = torch.rand(5, 20, 6)
alpha_t = torch.rand(5, 20)

In [124]:
alpha_t.unsqueeze(1).bmm(enc_hiddens).squeeze(1).size()

torch.Size([5, 6])

### Azure
Ganjahh123!

```
ssh -p 55336 scpdxcs@ml-lab-191a8958-5a9d-4291-83f4-565570e51159.southcentralus.cloudapp.azure.com
```

```
scp -r -P 55336 XCS224N-A4 scpdxcs@ml-lab-191a8958-5a9d-4291-83f4-565570e51159.southcentralus.cloudapp.azure.com:/home/scpdxcs/a4
```

```
scp -r -P 55336 scpdxcs@ml-lab-191a8958-5a9d-4291-83f4-565570e51159.southcentralus.cloudapp.azure.com:/home/scpdxcs/a4/XCS224N-A4/outputs outputs
```